FROM openjdk:11-jdk as build
RUN mkdir /workspace
RUN mkdir /workspace/app 

WORKDIR /workspace/app
COPY . .
COPY gradlew .
COPY gradle .
COPY build.gradle .
#RUN ./gradlew dependencies
RUN chmod -R 777 /workspace/app
#WORKDIR /workspace/app
RUN ./gradlew build
RUN mkdir -p build/dependency && (cd build/dependency; jar -xf ../libs/*.jar)
COPY /workspace/app/build/libs/*.jar Spring-Boot-docker-Storage.jar


ENTRYPOINT ["java","-jar","Spring-Boot-docker-Storage.jar"]
